"""Command pipeline for robot velocity processing.

Each incoming cmd_vel passes through a series of filters: speed limiter,
boundary filter, and collision filter. Each stage may modify the velocity
and generate events. All functions are pure — no ROS2 dependency.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from plato_pod.geometry import circle_to_polygon, polygon_contains_polygon
from plato_pod.kinematics_model import DifferentialDrive, KinematicsModel
from plato_pod.robot import Robot

_DEFAULT_KINEMATICS = DifferentialDrive()


@dataclass(frozen=True, slots=True)
class PipelineEvent:
    """An event generated by a pipeline stage."""
    event: str          # "boundary_contact", "collision_contact", "command_clamped"
    robot_id: int
    detail: dict


@dataclass(frozen=True, slots=True)
class PipelineResult:
    """Output of a pipeline stage or the full pipeline."""
    linear_x: float
    angular_z: float
    events: tuple[PipelineEvent, ...]




def speed_limit(
    linear_x: float,
    angular_z: float,
    max_linear: float,
    max_angular: float,
    robot_id: int,
) -> PipelineResult:
    """Clamp velocities to maximum allowed values.

    Args:
        linear_x: Commanded linear velocity (m/s).
        angular_z: Commanded angular velocity (rad/s).
        max_linear: Maximum linear speed.
        max_angular: Maximum angular speed.
        robot_id: Robot ID for event generation.

    Returns:
        PipelineResult with clamped velocities and optional command_clamped event.
    """
    clamped_lin = max(-max_linear, min(max_linear, linear_x))
    clamped_ang = max(-max_angular, min(max_angular, angular_z))

    events: list[PipelineEvent] = []
    if clamped_lin != linear_x or clamped_ang != angular_z:
        events.append(PipelineEvent(
            event="command_clamped",
            robot_id=robot_id,
            detail={
                "original_linear_x": linear_x,
                "original_angular_z": angular_z,
                "clamped_linear_x": clamped_lin,
                "clamped_angular_z": clamped_ang,
            },
        ))

    return PipelineResult(
        linear_x=clamped_lin,
        angular_z=clamped_ang,
        events=tuple(events),
    )


def predict_position(
    x: float, y: float, theta: float,
    linear_x: float, angular_z: float,
    dt: float,
    kinematics: KinematicsModel | None = None,
) -> tuple[float, float, float]:
    """Predict robot position after dt seconds using the given kinematics model.

    Args:
        x: Current X position.
        y: Current Y position.
        theta: Current heading (radians).
        linear_x: Linear velocity (m/s).
        angular_z: Angular velocity (rad/s).
        dt: Time step (seconds).
        kinematics: Motion model to use. Defaults to DifferentialDrive.

    Returns:
        Predicted (x', y', theta').
    """
    model = kinematics or _DEFAULT_KINEMATICS
    return model.predict(x, y, theta, linear_x, angular_z, dt)


def _check_position_valid(
    x: float, y: float, radius: float,
    boundary: tuple[tuple[float, float], ...],
    obstacles: list[tuple[tuple[float, float], ...]],
) -> tuple[bool, str | None, str | None]:
    """Check if a robot circle at (x, y) is valid.

    Returns:
        (valid, element_type, label) where element_type is "perimeter"
        or "obstacle" and label is the obstacle label (index-based).
    """
    if len(boundary) < 3:
        return True, None, None  # no boundary to enforce

    robot_poly = circle_to_polygon(x, y, radius, n_vertices=12)
    all_inside, _ = polygon_contains_polygon(list(boundary), robot_poly)
    if not all_inside:
        return False, "perimeter", "arena_boundary"

    for i, obs_verts in enumerate(obstacles):
        # Check if robot circle overlaps obstacle polygon
        # Simple approach: check if robot center is too close to obstacle
        # More precise: check if robot polygon intersects obstacle polygon
        from shapely.geometry import Polygon as ShapelyPolygon
        robot_shapely = ShapelyPolygon(robot_poly)
        obs_shapely = ShapelyPolygon(obs_verts)
        if robot_shapely.intersects(obs_shapely):
            return False, "obstacle", f"obstacle_{i}"

    return True, None, None


def boundary_filter(
    linear_x: float,
    angular_z: float,
    robot: Robot,
    boundary: tuple[tuple[float, float], ...],
    obstacles: list[tuple[tuple[float, float], ...]],
    lookahead_dt: float = 0.1,
    kinematics: KinematicsModel | None = None,
) -> PipelineResult:
    """Filter velocity to prevent boundary and obstacle crossing.

    Uses binary search to find the maximum safe velocity scaling.

    Args:
        linear_x: Linear velocity after speed limiting.
        angular_z: Angular velocity after speed limiting.
        robot: Current robot state.
        boundary: Arena boundary polygon.
        obstacles: List of obstacle polygons.
        lookahead_dt: Lookahead time in seconds.

    Returns:
        PipelineResult with clamped velocity and boundary_contact events.
    """
    if abs(linear_x) < 1e-6 and abs(angular_z) < 1e-6:
        return PipelineResult(linear_x=0.0, angular_z=0.0, events=())

    if len(boundary) < 3:
        return PipelineResult(linear_x=linear_x, angular_z=angular_z, events=())

    # Check if predicted position is valid
    px, py, _ = predict_position(
        robot.x, robot.y, robot.theta, linear_x, angular_z, lookahead_dt,
        kinematics,
    )
    valid, element_type, label = _check_position_valid(
        px, py, robot.radius, boundary, obstacles
    )

    if valid:
        return PipelineResult(linear_x=linear_x, angular_z=angular_z, events=())

    # Binary search for maximum safe velocity scaling
    lo, hi = 0.0, 1.0
    for _ in range(10):
        mid = (lo + hi) / 2.0
        mx, my, _ = predict_position(
            robot.x, robot.y, robot.theta,
            linear_x * mid, angular_z * mid, lookahead_dt,
            kinematics,
        )
        mid_valid, _, _ = _check_position_valid(
            mx, my, robot.radius, boundary, obstacles
        )
        if mid_valid:
            lo = mid
        else:
            hi = mid

    safe_scale = lo
    clamped_lin = linear_x * safe_scale
    clamped_ang = angular_z * safe_scale

    event = PipelineEvent(
        event="boundary_contact",
        robot_id=robot.robot_id,
        detail={
            "element": element_type,
            "label": label,
            "clamped": True,
        },
    )

    return PipelineResult(
        linear_x=clamped_lin,
        angular_z=clamped_ang,
        events=(event,),
    )


def collision_filter(
    linear_x: float,
    angular_z: float,
    robot: Robot,
    other_robots: list[Robot],
    lookahead_dt: float = 0.1,
    kinematics: KinematicsModel | None = None,
) -> PipelineResult:
    """Filter velocity to prevent robot-robot collision.

    Args:
        linear_x: Linear velocity after boundary filtering.
        angular_z: Angular velocity after boundary filtering.
        robot: Current robot state.
        other_robots: All other active robots.
        lookahead_dt: Lookahead time in seconds.

    Returns:
        PipelineResult with clamped velocity and collision_contact events.
    """
    if abs(linear_x) < 1e-6 and abs(angular_z) < 1e-6:
        return PipelineResult(linear_x=0.0, angular_z=0.0, events=())

    px, py, _ = predict_position(
        robot.x, robot.y, robot.theta, linear_x, angular_z, lookahead_dt,
        kinematics,
    )

    # Check for collision with each other robot
    colliding_robot: Robot | None = None
    for other in other_robots:
        if other.robot_id == robot.robot_id:
            continue
        dx = px - other.x
        dy = py - other.y
        dist = math.sqrt(dx * dx + dy * dy)
        min_dist = robot.radius + other.radius
        if dist < min_dist:
            colliding_robot = other
            break

    if colliding_robot is None:
        return PipelineResult(linear_x=linear_x, angular_z=angular_z, events=())

    # Binary search for safe scaling
    lo, hi = 0.0, 1.0
    for _ in range(10):
        mid = (lo + hi) / 2.0
        mx, my, _ = predict_position(
            robot.x, robot.y, robot.theta,
            linear_x * mid, angular_z * mid, lookahead_dt,
            kinematics,
        )
        safe = True
        for other in other_robots:
            if other.robot_id == robot.robot_id:
                continue
            dx = mx - other.x
            dy = my - other.y
            dist = math.sqrt(dx * dx + dy * dy)
            if dist < robot.radius + other.radius:
                safe = False
                break
        if safe:
            lo = mid
        else:
            hi = mid

    safe_scale = lo
    clamped_lin = linear_x * safe_scale
    clamped_ang = angular_z * safe_scale

    event = PipelineEvent(
        event="collision_contact",
        robot_id=robot.robot_id,
        detail={
            "other_robot_id": colliding_robot.robot_id,
            "clamped": True,
        },
    )

    return PipelineResult(
        linear_x=clamped_lin,
        angular_z=clamped_ang,
        events=(event,),
    )


def run_pipeline(
    linear_x: float,
    angular_z: float,
    robot: Robot,
    other_robots: list[Robot],
    boundary: tuple[tuple[float, float], ...],
    obstacles: list[tuple[tuple[float, float], ...]],
    max_linear: float = 0.2,
    max_angular: float = 2.0,
    lookahead_dt: float = 0.1,
    kinematics: KinematicsModel | None = None,
    terrain_speed_modifier: float = 1.0,
) -> PipelineResult:
    """Run the full command pipeline: speed limit → terrain → boundary → collision.

    Args:
        linear_x: Raw commanded linear velocity.
        angular_z: Raw commanded angular velocity.
        robot: Current robot state.
        other_robots: All other active robots.
        boundary: Arena boundary polygon.
        obstacles: Obstacle polygons.
        max_linear: Maximum linear speed.
        max_angular: Maximum angular speed.
        lookahead_dt: Lookahead time for prediction.
        kinematics: Motion model for position prediction. Defaults to DifferentialDrive.
        terrain_speed_modifier: Terrain-based speed scaling factor (0.0–1.0).
            Values below 1.0 simulate uphill movement, rough terrain, etc.
            Applied after speed limiting, before boundary/collision checks.

    Returns:
        PipelineResult with final velocity and all generated events.
    """
    all_events: list[PipelineEvent] = []

    # Stage 1: speed limit
    r1 = speed_limit(linear_x, angular_z, max_linear, max_angular, robot.robot_id)
    all_events.extend(r1.events)

    # Stage 2: terrain speed modifier
    lin = r1.linear_x
    ang = r1.angular_z
    if terrain_speed_modifier < 1.0:
        modifier = max(0.0, min(1.0, terrain_speed_modifier))
        lin *= modifier
        ang *= modifier

    # Stage 3: boundary + obstacle filter
    r2 = boundary_filter(
        lin, ang, robot, boundary, obstacles, lookahead_dt,
        kinematics,
    )
    all_events.extend(r2.events)

    # Stage 4: collision filter
    r3 = collision_filter(
        r2.linear_x, r2.angular_z, robot, other_robots, lookahead_dt,
        kinematics,
    )
    all_events.extend(r3.events)

    return PipelineResult(
        linear_x=r3.linear_x,
        angular_z=r3.angular_z,
        events=tuple(all_events),
    )
